# Generated by Django 4.2.3 on 2023-08-03 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker_symbol', models.IntegerField()),
                ('acquisition_stock_price', models.IntegerField()),
                ('number_of_shares_purchased', models.IntegerField()),
                ('simulation_stock_price', models.IntegerField()),
            ],
        ),
    ]
