# Generated by Django 4.2.3 on 2023-08-05 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_trading_simulation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockinformation',
            name='acquisition_stock_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stockinformation',
            name='number_of_shares_purchased',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stockinformation',
            name='simulation_stock_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stockinformation',
            name='ticker_symbol',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
