# Generated by Django 4.2.3 on 2023-08-24 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_trading_simulation', '0002_alter_stockinformation_acquisition_stock_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockinformation',
            name='acquisition_stock_price_fall_5per',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockinformation',
            name='acquisition_stock_price_fall_5per_profit_and_loss',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockinformation',
            name='company_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockinformation',
            name='market_capitalization_at_time_of_purchase',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockinformation',
            name='simulation_stock_profit_and_loss',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockinformation',
            name='stock_price_down_5per',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
