# Generated by Django 4.2.3 on 2023-08-26 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_trading_simulation', '0004_stockinformation_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockinformation',
            name='user',
        ),
    ]
