# Generated by Django 4.2.3 on 2023-09-06 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_trading_simulation', '0008_alter_stockinformation_acquisition_stock_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockinformation',
            name='simulation_stock_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
