# Generated by Django 4.2.3 on 2023-09-13 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_trading_simulation', '0009_alter_stockinformation_simulation_stock_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockinformation',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
