# Generated by Django 4.2.3 on 2023-09-25 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_trading_simulation', '0010_stockinformation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockinformation',
            name='acquisition_stock_price_fall_10per',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockinformation',
            name='acquisition_stock_price_fall_10per_profit_and_loss',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockinformation',
            name='acquisition_stock_price_fall_30per',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockinformation',
            name='acquisition_stock_price_fall_30per_profit_and_loss',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockinformation',
            name='stock_price_down_10per',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockinformation',
            name='stock_price_down_30per',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
